// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPNZjM2__jO1AqXuc1G80_EzhLoybsyiI',
    appId: '1:442757339922:web:a929ccb2425313eaa731cb',
    messagingSenderId: '442757339922',
    projectId: 'flutter-storage-e8a3d',
    authDomain: 'flutter-storage-e8a3d.firebaseapp.com',
    storageBucket: 'flutter-storage-e8a3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPYM-WMok2n3Zkn-Ve2PqG0xubbHZOjaY',
    appId: '1:442757339922:android:81c762a4f1d9b255a731cb',
    messagingSenderId: '442757339922',
    projectId: 'flutter-storage-e8a3d',
    storageBucket: 'flutter-storage-e8a3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl3Cdn5o2NuikTqPpjV82t-io2i992kBo',
    appId: '1:442757339922:ios:0af991f6dcff8223a731cb',
    messagingSenderId: '442757339922',
    projectId: 'flutter-storage-e8a3d',
    storageBucket: 'flutter-storage-e8a3d.appspot.com',
    iosClientId: '442757339922-51qthkk90vqs9h5kaa1ur4grv9oamf31.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStorageFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl3Cdn5o2NuikTqPpjV82t-io2i992kBo',
    appId: '1:442757339922:ios:02e39697a141b20ba731cb',
    messagingSenderId: '442757339922',
    projectId: 'flutter-storage-e8a3d',
    storageBucket: 'flutter-storage-e8a3d.appspot.com',
    iosClientId: '442757339922-rsdt3rkmukpsj2gdqtp17tq1tglggtto.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStorageFirebase.RunnerTests',
  );
}
